### ISSUE TITLE
No blacklist/whitelist/config for campfire-friendly furnace recipes.

### ISSUE THREAD

**Issue by Ski-z** [jbredwards/Campfire-Mod#5]
I've been looking for a 1.12.2 campfire mod that would allow me to add my own recipes. Is there any chance you could add a blacklist/whitelist to the config? One that can read Crafttweaker furnace recipes, including those added by Crafttweaker?

 

For metadata example, if you place toughasnails:canteen,1 on the fire, it turns into toughasnails:canteen,2.

Or with NBT: simpledifficulty:canteen{Fluid:water} turns into simpledifficulty:canteen{Fluid:purified_water}

 

If you think it's doable, I'd love to pay a commission. Feel free to DM me.

**Comment by jbredwards** [comment]
Resolved via dm, for anyone looking for the solution:

Campfire adds a file inside the `.minecraft/config/campfire` folder called `recipes.json`, which has two main parts: it can either add recipes or remove them, example:
```java
{
    "add":[
        //recipe that turns a dirt into a diamond, with no exp output and that takes 400 ticks (default value)
        {"inputs":[{"id":"minecraft:dirt"}], "output":{"id":"minecraft:diamond"}},
        //recipe that turns a course dirt into an emerald, the recipe is set to only work on oak log campfires
        {"inputs":[{"id":"minecraft:dirt","Damage":1}],"output":{"id":"minecraft:emerald"},"campfireTypes":[{"id":"minecraft:log"}]},
        //recipe that turns wool (with any damage value) into a stone block, takes 500 ticks and gives 1 xp
        {"inputs":[{"id":"minecraft:wool","Damage":32767}],"output":{"id":"minecraft:stone"},"experience":1,"cookTime":500}
    ],
    "remove":[
        //the "input" tag removes any recipes that use the provided ItemStack as an input
        {"input":{"id":"minecraft:porkchop"}},
        //the "output" tag removes any recipes that use the provided ItemStack as an output
        {"output":{"id":"minecraft:cooked_fish","Damage":1}}
    ]
}
```
